source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'ZeroKit' do
    pod 'SnapKit'
    #pod 'SDWebImage'
    #pod 'Alamofire'
    #pod 'Moya'
    #pod 'RxSwift'
    #pod 'RxCocoa'
    
end
